name: Build and Test .NET API

on:
  push:
    branches: [ dev, test ]  # ramas que activan la CI
  pull_request:
    branches: [ dev, test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v3

      - name: ⚙️ Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: 📦 Restaurar dependencias
        run: dotnet restore ApiTest/ApiTest.csproj

      - name: 🛠️ Compilar solución
        run: dotnet build ApiTest/ApiTest.csproj --no-restore --configuration Release

      # - name: ✅ Ejecutar tests (si tenés)
      #   run: dotnet test ApiTest/ApiTest.csproj --no-build --verbosity normal
